kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc
spec:
  storageClassName: "###ZARF_VAR_NFS_STORAGE_CLASS###"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ###ZARF_VAR_NFS_STORAGE_SIZE###