nextcloud:
  username: ###ZARF_VAR_NEXTCLOUD_USERNAME###
  password: ###ZARF_VAR_NEXTCLOUD_PASSWORD###
  extraInitContainers:
  - name: postgresql-isready
    image: bitnami/postgresql:14.4.0-debian-11-r23
    env:
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: nextcloud-nextcloud-db
            key: db-username
    command:
      - "sh"
      - "-c"
      - "until pg_isready -h nextcloud-nextcloud-postgresql -U ${POSTGRES_USER} ; do sleep 2 ; done"

  host: ###ZARF_VAR_NEXTCLOUD_HOST###
  configs:
    domains.config.php: |-
      <?php
      $CONFIG = array (
        'trusted_domains' =>
          array (
          0 => 'localhost',
          1 => '###ZARF_VAR_NEXTCLOUD_HOST###',
          )
      );
    overwrite.config.php: |-
      <?php
      $CONFIG = array (
        'overwriteprotocol' => 'https',
      );

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true

  ## Supported database engines: mysql or postgresql
  type: postgresql

  user: nextcloud

  ## Database password
  password: replaceme

  ## Database host
  host: nextcloud-nextcloud-postgresql.nextcloud.svc.cluster.local:5432
  ## Database name
  database: nextcloud

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 10Gi

  nextcloudData:
    enabled: true
    storageClass: "###ZARF_VAR_NEXTCLOUD_DATA_STORAGE_CLASS###"
    accessMode: ReadWriteOnce
    size: ###ZARF_VAR_NEXTCLOUD_DATA_STORAGE_SIZE###