kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tabby-pvc
spec:
  storageClassName: "###ZARF_VAR_TABBY_STORAGE_CLASS###"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ###ZARF_VAR_TABBY_STORAGE_SIZE###